# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LifeTrack' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LifeTrack
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'Firebase/Core', '~> 5.15.0'
  pod 'RNSound', :path => '../node_modules/react-native-sound'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  target 'LifeTrackTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
